// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: docs/proto/v1/post.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category int32

const (
	Category_CATEGORY_UNSPECIFIED Category = 0
	Category_FEED                 Category = 1
	Category_STORY                Category = 2
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "FEED",
		2: "STORY",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED": 0,
		"FEED":                 1,
		"STORY":                2,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_docs_proto_v1_post_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_docs_proto_v1_post_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_docs_proto_v1_post_proto_rawDescGZIP(), []int{0}
}

// Request message for GetPostById.
type GetPostByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostByIdRequest) Reset() {
	*x = GetPostByIdRequest{}
	mi := &file_docs_proto_v1_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostByIdRequest) ProtoMessage() {}

func (x *GetPostByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPostByIdRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_post_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response message for GetPostById.
type GetPostByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Category      Category               `protobuf:"varint,4,opt,name=category,proto3,enum=grpc.v1.Category" json:"category,omitempty"`
	CreateTime    string                 `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostByIdResponse) Reset() {
	*x = GetPostByIdResponse{}
	mi := &file_docs_proto_v1_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostByIdResponse) ProtoMessage() {}

func (x *GetPostByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPostByIdResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_post_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostByIdResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPostByIdResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetPostByIdResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetPostByIdResponse) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *GetPostByIdResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *GetPostByIdResponse) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

var File_docs_proto_v1_post_proto protoreflect.FileDescriptor

const file_docs_proto_v1_post_proto_rawDesc = "" +
	"\n" +
	"\x18docs/proto/v1/post.proto\x12\agrpc.v1\"$\n" +
	"\x12GetPostByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc6\x01\n" +
	"\x13GetPostByIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12-\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x11.grpc.v1.CategoryR\bcategory\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x06 \x01(\tR\n" +
	"updateTime*9\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04FEED\x10\x01\x12\t\n" +
	"\x05STORY\x10\x022P\n" +
	"\x04Post\x12H\n" +
	"\vGetPostById\x12\x1b.grpc.v1.GetPostByIdRequest\x1a\x1c.grpc.v1.GetPostByIdResponseB\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_docs_proto_v1_post_proto_rawDescOnce sync.Once
	file_docs_proto_v1_post_proto_rawDescData []byte
)

func file_docs_proto_v1_post_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_post_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_post_proto_rawDesc), len(file_docs_proto_v1_post_proto_rawDesc)))
	})
	return file_docs_proto_v1_post_proto_rawDescData
}

var file_docs_proto_v1_post_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_docs_proto_v1_post_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_docs_proto_v1_post_proto_goTypes = []any{
	(Category)(0),               // 0: grpc.v1.Category
	(*GetPostByIdRequest)(nil),  // 1: grpc.v1.GetPostByIdRequest
	(*GetPostByIdResponse)(nil), // 2: grpc.v1.GetPostByIdResponse
}
var file_docs_proto_v1_post_proto_depIdxs = []int32{
	0, // 0: grpc.v1.GetPostByIdResponse.category:type_name -> grpc.v1.Category
	1, // 1: grpc.v1.Post.GetPostById:input_type -> grpc.v1.GetPostByIdRequest
	2, // 2: grpc.v1.Post.GetPostById:output_type -> grpc.v1.GetPostByIdResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_post_proto_init() }
func file_docs_proto_v1_post_proto_init() {
	if File_docs_proto_v1_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_post_proto_rawDesc), len(file_docs_proto_v1_post_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_post_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_post_proto_depIdxs,
		EnumInfos:         file_docs_proto_v1_post_proto_enumTypes,
		MessageInfos:      file_docs_proto_v1_post_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_post_proto = out.File
	file_docs_proto_v1_post_proto_goTypes = nil
	file_docs_proto_v1_post_proto_depIdxs = nil
}
