// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/1111mp/gin-app/ent/accesstoken"
)

// AccessTokenCreate is the builder for creating a AccessToken entity.
type AccessTokenCreate struct {
	config
	mutation *AccessTokenMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *AccessTokenCreate) SetCreateTime(v time.Time) *AccessTokenCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *AccessTokenCreate) SetNillableCreateTime(v *time.Time) *AccessTokenCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *AccessTokenCreate) SetUpdateTime(v time.Time) *AccessTokenCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *AccessTokenCreate) SetNillableUpdateTime(v *time.Time) *AccessTokenCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AccessTokenCreate) SetName(v string) *AccessTokenCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *AccessTokenCreate) SetValue(v string) *AccessTokenCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetOwner sets the "owner" field.
func (_c *AccessTokenCreate) SetOwner(v int) *AccessTokenCreate {
	_c.mutation.SetOwner(v)
	return _c
}

// SetExpireTime sets the "expire_time" field.
func (_c *AccessTokenCreate) SetExpireTime(v int64) *AccessTokenCreate {
	_c.mutation.SetExpireTime(v)
	return _c
}

// SetCreator sets the "creator" field.
func (_c *AccessTokenCreate) SetCreator(v int) *AccessTokenCreate {
	_c.mutation.SetCreator(v)
	return _c
}

// Mutation returns the AccessTokenMutation object of the builder.
func (_c *AccessTokenCreate) Mutation() *AccessTokenMutation {
	return _c.mutation
}

// Save creates the AccessToken in the database.
func (_c *AccessTokenCreate) Save(ctx context.Context) (*AccessToken, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccessTokenCreate) SaveX(ctx context.Context) *AccessToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccessTokenCreate) defaults() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		if accesstoken.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized accesstoken.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := accesstoken.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		if accesstoken.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized accesstoken.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := accesstoken.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccessTokenCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "AccessToken.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "AccessToken.update_time"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AccessToken.name"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "AccessToken.value"`)}
	}
	if _, ok := _c.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required field "AccessToken.owner"`)}
	}
	if _, ok := _c.mutation.ExpireTime(); !ok {
		return &ValidationError{Name: "expire_time", err: errors.New(`ent: missing required field "AccessToken.expire_time"`)}
	}
	if _, ok := _c.mutation.Creator(); !ok {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required field "AccessToken.creator"`)}
	}
	return nil
}

func (_c *AccessTokenCreate) sqlSave(ctx context.Context) (*AccessToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccessTokenCreate) createSpec() (*AccessToken, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accesstoken.Table, sqlgraph.NewFieldSpec(accesstoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(accesstoken.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(accesstoken.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(accesstoken.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(accesstoken.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Owner(); ok {
		_spec.SetField(accesstoken.FieldOwner, field.TypeInt, value)
		_node.Owner = value
	}
	if value, ok := _c.mutation.ExpireTime(); ok {
		_spec.SetField(accesstoken.FieldExpireTime, field.TypeInt64, value)
		_node.ExpireTime = value
	}
	if value, ok := _c.mutation.Creator(); ok {
		_spec.SetField(accesstoken.FieldCreator, field.TypeInt, value)
		_node.Creator = value
	}
	return _node, _spec
}

// AccessTokenCreateBulk is the builder for creating many AccessToken entities in bulk.
type AccessTokenCreateBulk struct {
	config
	err      error
	builders []*AccessTokenCreate
}

// Save creates the AccessToken entities in the database.
func (_c *AccessTokenCreateBulk) Save(ctx context.Context) ([]*AccessToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccessToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccessTokenCreateBulk) SaveX(ctx context.Context) []*AccessToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
