-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "user_name_email" to table: "users"
CREATE INDEX "user_name_email" ON "users" ("name", "email");
-- create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- create index "users_name_key" to table: "users"
CREATE UNIQUE INDEX "users_name_key" ON "users" ("name");
-- set comment to table: "users"
COMMENT ON TABLE "users" IS 'User table stores all user information.';
-- create "posts" table
CREATE TABLE "posts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "title" character varying NOT NULL, "content" character varying NULL, "category" character varying NOT NULL, "user_posts" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "posts_users_posts" FOREIGN KEY ("user_posts") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "post_title_user_posts" to table: "posts"
CREATE UNIQUE INDEX "post_title_user_posts" ON "posts" ("title", "user_posts");
-- set comment to table: "posts"
COMMENT ON TABLE "posts" IS 'Post table stores all post information.';
