basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a sample server Petstore server.
  title: Go Clean Template API
  version: "1.0"
paths:
  /user/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve user information by given user ID
      operationId: getUserById
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get user by ID
      tags:
      - user
swagger: "2.0"
